---
bibliography: references.bib
number-sections: true
---

# Design doc for extending to other outcomes (count, survival, binary)

Currently, `rbmi` only supports continuous endpoints. However, also for other commonly used endpoints, in particular count, survival and binary endpoints, multiple imputation is often needed. Both the name of the `rbmi` package, as well as the structure of the workflow, would also fit these other endpoint methods for (reference based) multiple imputation. 

## Methodology overview

Here is a first high level overview of important references for the non-continuous endpoints:

### Count outcomes

- @keene2014 is the basic proposal for Bayesian multiple imputation for negative binomial count data, covering two time periods: before and after discontinuing the trial and treatment at the same time.
- @roger2019 extends this to more than two time periods, in particular a third time period where patients are still continuing the trial, but have stopped treatment already. So this is the more general setting.

Time to recurrent events can also be analyzed with Andersen-Gill models, but we will not pursue this further here.

### Survival outcomes 

- @lu2015 compare delta-adjustment and reference-based multiple imputation methods:
  - The delta-adjustment method assumes a multiplicative increase of the hazard for patients who discontinue the treatment early in the experimental arm, but the same hazard as continuing control patients for control patients who discontinue.
  - The reference-based method assumes that the hazard after discontinuation is in between control and experimental patients (factor $1 - \phi$ is multiplied with $\beta$ to obtain new log hazard ratio). It basically corresponds to "copy reference" approach in longitudinal data, not clear how "jump to reference" would work in survival.
  - The draw model fit uses `SAS PHREG` with the `bayes` statement. An option is to use piecewise constant hazards. Therefore they use either interpolated Breslow estimate or piecewise exponential model to get the baseline hazard.
  - For the imputation, they propose both a Bayesian as well as a frequentist MLE approach, and then just draw from the conditional distribution given the censoring time. Interestingly they still censor the observations at the next planned visit.
  - In the analysis step they just use stanard Cox proportional hazards models, and then combine them with Rubin's rules.
- @atkinson2019 propose reference based multiple imputation:
  - They argue that Rubin's rules lead to "information-anchored" inference, which gives a "level playing field" and should be ok to use
  - For the draw model they propose a simple Weibull proportional hazards model, fit with maximum likelihood and then draw from the asymptotic normal distribution of the parameters
  - For the imputation they distinguish the different assumptions:
    - censored at random (CAR): just use the conditional distribution of the survival time given the covariates and censoring time as well as the parameters drawn from the draw step
    - jump to reference (J2R): the hazard changes after the censoring time immediately to that of the control group. The authors mention that this corresponds to "copy reference" (CR) from longitudinal modeling but I don't really see that ...
    - copy increment from reference (CIR): the the hazard ratio is taken from the censoring time and then multiplied with reference hazard to obtain the hazard after the censoring time. So this is additive on the log hazard scale.
    - delta method: the hazard after the censoring time is multiplied with a factor $\delta$, given by the user.
  - The analysis model is again the same Weibull PH model as for the draw step, but now fit to the imputed data sets, and then combined with Rubin's rules.
- @hartley2022 extend the idea from the neg bin/count imputation using on/off treatment periods from @roger2019 to survival outcomes:
  - Note that they describe this as different from reference based multiple imputation
  - Similar as for counts, also here allow different off treatment imputation models:
    - either all have the same hazard after discontinuing treatment
    - or the step change is the same for all
    - or the arms have individual off treatment hazards (this will need the most observed off treatment data to be able to fit the model)
  - Proposed steps are:
    - They bootstrap observed data using cluster sampling
    - For each bootstrapped data set they fit an Andersen-Gill model (which is the same here as a Cox PH model, right?), including the same covariates as for the analysis model
    - Then they impute any missing times to event in the original dataset using the estimates from each bootstrapped data set
      - Note that this is not exactly the same as in the continuous rbmi approach described [here](https://openpharma.github.io/rbmi/latest-tag/articles/stat_specs.html#bootstrapped-mi)
    - Then they fit the analysis model (Cox model) to each imputed data set and pool using Rubin’s rules
  - They highlight that it is problematic to use the Cox model when we have piece wise hazard functions - we no longer have the PH assumption fulfilled!
    - As an alternative, they propose the restricted mean survival time (RMST), estimated here as an integral of the Kaplan-Meier curve
  - SAS code available at [github.com/GSK-Biostatistics/mi_off_trt](https://github.com/GSK-Biostatistics/mi_off_trt)
- @garcia2024 propose an analytical solution for delta adjustment and reference-based imputation with time-to-event endpoints
  - It has a nice table with a literature overview (but misses the @hartley2022 paper in there)
  - I did not go into detail here because it is not in scope (no MI)

For our purposes, for survival outcomes we are going to:

- Focus on Bayesian multiple imputation. Bootstrap could be added later if needed (it considers a different variance estimand) and is not a priority.
- Focus are reference based imputation methods (especially "jump to reference" and "copy increments from reference"), but off-treatment imputation methods can also be beneficial to have. As mentioned below in @sec-outcome-structure, the data structure for survival outcomes is similar to that for count outcomes also in this regard.
- The delta method is needed as part of a tipping point analysis. There is also a Novartis R package for this particular approach, which could be used for comparison of results. 
- Different baseline hazard models need to be supported, in particular exponential, Weibull and piecewise constant (exponential) hazards.


### Binary

- @cro2025 describe two algorithms for reference-based multiple imputation for binary outcomes:
  - The first uses joint modeling with the multivariate normal distribution and an adaptive rounding algorithm. This is basically using the continuous outcomes approach and then just "rounds back" post-ICE sampled outcome values to 0 and 1 by looking at the samples distribution and assuming a normal shape of it.
  - The second uses joint modeling too, but with a latent multivariate normal model, that corresponds to a multivariate probit model for the binary outcomes. The computation is a bit more involved, the authors mention specialized MCMC samplers which are e.g. implemented in the [`jomo`](https://cran.r-project.org/web/packages/jomo/index.html) R package. Fortunately multivariate probit models can also be fitted with Stan, see [here](https://mc-stan.org/docs/stan-users-guide/regression.html#multivariate-probit-regression) for details. This could be a better starting point for inclusion in the `rbmi` package.
  - The paper makes the assumption that all post-ICE binary outcomes are missing.
  - They use a logistic regression model at a certain time point/visit as the analysis model, and then combine the results with Rubin's rules.
- @rehal2026 treat the more general case where a part of the patients is still observed after treatment discontinuation (similar as in the negative binomial and survival papers).
  - A good point they make is that if the underlying outcome is truly continuous then this should be used for imputation instead - however this may be difficult if that outcome is complex! (think about response in oncology studies, where e.g. the RECIST definition is quite complex although it mainly looks at a continuous outcome, the sum of longest diameters of the target lesions)
  - They use sequential, iterative imputation at each timepoint, separately within each treatment arm - i.e. at each sequence k step it can use both observed and previously imputed data from time points before k (by treating them as covariates)
  - They propose different conditional regression models:
    - CICS (common intercepts common slopes)
    - POOLED OICS (On/Off Intercepts common slopes) - just have an intercept change based on treatment status 
    - OICS - same but with treatment arm specific parameter estimates (intercepts delta_zj)
    - OITS - same but with additional time since discontinuation as covariate same as OICS but with additional pattern indicators (ordinal covariate)
    - FULL - as reference also fitted full model on all observed data
  - OICS seems most promising based on simulation study results - distinction needs to be made between the pre-and post-IE data and this should be reflected appropriately in MI models to impute the missing data 
  - They propose to use a pragmatic step-down process when the rate of intercurrent events and missing data are is not clear before the study, i.e. start with the most complex imputation model and only if that fails use the next less complex one etc.
  - They mention perfect prediction / linear separation issue with logistic regression - I wonder if it would be relatively easy to mitigate this with regularization / prior on the regression coefficients.


### Outcome structure {#sec-outcome-structure}

For the current longitudinal continuous outcome, the structure is that of multiple visits (i.e. preplanned time-points) with a continuous outcome at each visit. This is the same for binary outcomes (e.g. response, relapse, etc.), which are often also measured at the same time-points as the continuous outcomes. Off-treatment modelling for continuous and binary outcomes can be done in a simple way by including an indicator variable for being on/off treatment in the imputation model.
Missing data occurs because of intercurrent events or missed visits, and the missingness is defined for each visit.

For count outcomes, the structure is different: In the best case where a patient starts treatment and continues it until the end of the trial, we have a single count at the end of the trial. If we have treatment discontinuation and trial drop-out, we can have a maximum of three time periods: (1) before discontinuing the trial and treatment, (2) after discontinuing the treatment but still in the trial, and (3) after discontinuing the trial and treatment.
After discontinuing the trial, we cannot observe the outcome any longer, and therefore we have missing data for the count outcome in period (3).

For survival outcomes, the structure is similar as for count outcomes: Ideally we have a single survival time at the end of the trial (either the patient had an event before, or the patient is censored at the end of the trial). If we have treatment discontinuation and trial drop-out, we can again have a maximum of three time periods as for count outcomes. At the time of trial discontinuation the patient becomes immediately censored.

### Available imputation methods

For all new outcomes, we initially focus on Bayesian multiple imputation methods.
We can then always use the `rbmi` workflow steps as follows:

- Draw: Fit the initial imputation model via MCMC and draw parameters from the posterior distribution. 
- Impute: Use the drawn parameters and the assumed model to impute the missing data for each parameter draw.
- Analyse: Analyse each of the imputed datasets with a (fast) analysis model, and save relevant estimators.
- Pool: Pool the estimators across the imputed datasets to get a single point estimate and confidence interval.

It seems that the other imputation methods, such as conditional mean imputation, are (for now) not relevant and therefore not supported.

Note that the above 4-step workflow assumes a joint model across all timepoints, which is first fitted to the data in the Draw step and then used to impute all missing data in the Impute step. Thus the sequential imputation approach as described in @rehal2026 for binary outcomes is not well in scope.

## User interface generalization

### Data

- For count and survival outcomes, the same `expand_locf()` function can be used: Instead of the visit variable, we use a "period" or "phase" variable, which indicates whether the patient is in period (1), (2) or (3) as described above. 
- For count outcomes, we have then in addition a "count" variable, capturing counts for each of the three periods, as well as a "duration" variable capturing the duration of each period (e.g. in years). 
- For survival outcomes, we also need in addition two variables:
  - The "event" variable, which is a binary variable indicating whether the patient had an event in the time period or continued without an event (i.e. censored if next time period is not observable)
  - The "time" variable, which captures either the time to event in the period where there was an event, or the duration of the period if there was no event (i.e. censored).

### Draws

The `draws()` function needs to take the following inputs:

- `outcome`: The outcome type, which defaults to "continuous" (current implementation), but can now also be "count", "survival" or "binary". 
- `data`: The whole data as described above
- `data_ice`: The data with intercurrent events (ICE) time points (that lead to discontinuation of follow up) and imputation strategies, which include:
  - Missing At Random: "MAR"
  - Jump to Reference: "JR"
  - Copy Reference: "CR"
  - Copy Increments from Reference: "CIR"
  - Last Mean Carried Forward: "LMCF"
- `data_treatment_ice`: Only needed for count and survival outcomes, the data with treatment discontinuation time points and corresponding off-treatment imputation strategies.
  - TODO: We might need to be able to specify different strategies here
  - TODO: Make sure that we don't have duplicate information with `data_ice`
- `vars`: In addition to the existing variables, where we use `outcome` to capture counts and binary outcomes, we also need `event` and `time` for survival outcomes, and `duration` for count outcomes.
- `method`: For now we will only support `method_bayes()`, but could later support additional methods via corresponding `method_*()` constructors.
  - Here we need to be able to specify the survival model when used together with survival outcomes (in the similar way as now we specify the covariance model for continuous outcomes).

### Impute

The `impute()` function takes the `draws` object and the reference group mapping, and internally produces the imputed data sets.
For this to work correctly with different outcome types, the `draws` object needs to have a second (or a more specific) class indicating the outcome type, e.g. `draws_continuous`, `draws_count`, `draws_survival` and `draws_binary`. The `impute()` function can then dispatch on this second class to use the correct imputation method for the different outcome types.

Similarly, the result of the `impute()` call needs to have a second class indicating the outcome type, e.g. `imputation_continuous`, `imputation_count`, `imputation_survival` and `imputation_binary`. This allows the `analyse()` function to dispatch on the correct analysis method for the different outcome types.

### Analyse

In the last step of the workflow, the user chosen analysis model is applied to each of the imputed datasets, and the relevant estimators are saved for pooling. Because we can dispatch on the outcome type, we might have slightly different arguments supported here.

In addition, `rbmi` can provide the standard analysis functions for the different outcome types. For example:

- For count outcomes we can provide a `neg_bin_regression` function,
- for survival outcomes a `cox_regression()` function, 
- and for binary outcomes a `logistic_regression()` function.

Also optional marginalized treatment effect estimators and differences can be valuable (e.g. via an `rmst()` function for restricted mean survival time analysis). We can utilize the [`RobinCar2`](https://openpharma.github.io/RobinCar2/latest-tag/) for this instead of implementing it from scratch.

### Pool

Here we just want to use Rubin's rules to pool the Bayesian multiple imputation results across the imputed datasets. 

We initially considered to add an argument `df` or so to define the calculation of the degrees of freedom, because SAS uses a different method and we might want to be able to reproduce that with `rbmi` if needed. However we discussed and since we anyway only pool asymptotically normally distributed test statistics, we can just set the degrees of freedom to infinity and use thereby the normal distribution for the confidence interval calculation. 

Note that this also requires care about the scale at which the pooling is performed: e.g. for survival outcomes we can use the log hazard ratio scale for pooling, which is asymptotically normal, but not the hazard ratio scale itself. Similarly for count outcomes we can use the log rate ratio scale, and for binary outcomes the log odds ratio scale.

## Internal structure adaptation

### Draws

The `draws()` function needs to be adapted as described above for the user interface. Internally, this means both the generic function as well as the `draws.bayes()` method need to be changed, while the other methods can almost stay as is (they should just assert that the outcome type is "continuous").

Internally, `draws.bayes()` can then dispatch on the outcome type for the correct code path, keeping the current behavior as is for the "continuous" outcome type. In particular, the `fit_mcmc()` function need to also dispatch on the different outcome types, to fit the correct imputation model and draw parameters from the posterior distribution: Instead of calling `fit_mmrm()` for the continuous outcome type, we can call `fit_neg_multinom()` for the count outcome type e.g. However, many of the logistics around the MCMC fitting and parameter drawing can be kept the same across the different outcome types, so we can reuse a lot of code here.

The new fitting functions would use new Stan code from `inst/stan/` for the different outcome types, which would be added to the package. 

Also the post-processing is slightly different depending on outcome. Finally, the `as_draws()` constructor now also attaches the additional class for the outcome type, as described above.

### Impute

For the `impute()` function, we primarily need to change the `impute.random()` method, which needs to dispatch on the outcome type for the correct code path. This means changing `impute_internal()` and the workhorse `impute_data_individual()`, which currently calls `impute_outcome()` which in turn generates multivariate normal samples. In contrast, for the count outcome type e.g., we would need to generate negative binomial samples at the end.

For both the `draws()` and `impute()` steps, we will need to make sure we use the two data sets for intercurrent events and treatment discontinuation correctly for count and survival outcomes. It might also involve having a time-varying covariate to account for the on/off treatment status in the imputation model.

### Analyse

Looking at the `analyse()` function's stack [here](https://github.com/openpharma/rbmi/blob/main/R/analyse.R) it seems that most of the code won't need to be adapted a lot. The dispatching on outcome type will matter for small things like the initial input validation only. The most important additions will be the outcome type specific analysis functions, supplementing the existing [ANCOVA](https://github.com/openpharma/rbmi/blob/main/R/ancova.R) function.

### Pool

There is not much to change here.
As mentioned above we initially considered to have a `df` argument to be able to optionally choose the simpler degrees of freedom calculation, along these lines (compare [here](https://documentation.sas.com/doc/en/statug/latest/statug_mianalyze_details08.htm)):

```{r}
#| eval: false
df_sas <- (M - 1) * (1 + within_var / ((1 + 1/M) * between_var))^2
df_sas
t_crit_sas <- qt(1 - alpha/2, df_sas)
ci_lower_sas <- coef_hat - t_crit_sas * coef_se
ci_upper_sas <- coef_hat + t_crit_sas * coef_se
```

However, as mentioned above, we decided to just use `qnorm()` instead for simplicity.

## References
