#' Analysis of Covariance
#'
#' Performs an analysis of covariance between two or more treatment groups returning the
#' estimated "treatment effect" (i.e. the contrast between treatment groups) and
#' the least square means estimates in each group.
#'
#' @param data A `data.frame` containing the data to be used in the model.
#' @param vars A `vars` object as generated by [set_vars()]. Only the `group`,
#' `visit`, `outcome` and `covariates` elements are required. See details.
#' @param visits An optional character vector specifying which visits to
#' fit the ANCOVA model at. If `NULL`, a separate ANCOVA model will be fit to the
#' outcomes for each visit (as determined by `unique(data[[vars$visit]])`).
#' See details.
#' @param weights Character, either `"counterfactual"` (default), `"equal"`,
#' `"proportional_em"` or `"proportional"`.
#' Specifies the weighting strategy to be used when calculating the lsmeans.
#' See the weighting section for more details.
#'
#' @details
#' The function works as follows:
#'
#' 1. Select the first value from `visits`.
#' 2. Subset the data to only the observations that occurred on this visit.
#' 3. Fit a linear model as  `vars$outcome ~ vars$group + vars$covariates`.
#' 4. Extract the "treatment effect" & least square means for each treatment group.
#' 5. Repeat points 2-3 for all other values in `visits`.
#'
#' If no value for `visits` is provided then it will be set to
#' `unique(data[[vars$visit]])`.
#'
#' In order to meet the formatting standards set by [analyse()] the results will be collapsed
#' into a single list suffixed by the visit name, e.g.:
#'```
#'list(
#'    trt_visit_1 = list(est = ...),
#'    lsm_ref_visit_1 = list(est = ...),
#'    lsm_alt_visit_1 = list(est = ...),
#'    trt_visit_2 = list(est = ...),
#'    lsm_ref_visit_2 = list(est = ...),
#'    lsm_alt_visit_2 = list(est = ...),
#'    ...
#')
#'```
#' `ancova()` supports two or more treatment groups. The group levels are referred to
#' via a fixed naming scheme derived from the factor levels of `vars$group`: `ref` is the
#' first factor level, `alt` the second, `alt2` the third, `alt3` the fourth, and so on.
#' Note that `ref` does not necessarily coincide with the control arm; it is simply the
#' first factor level.
#'
#' The least square means for each group are returned as `lsm_ref`, `lsm_alt`, `lsm_alt2`,
#' etc. Treatment effects (model contrasts) are returned as `trt` for the `alt` vs `ref`
#' comparison, `trt_alt2` for `alt2` vs `ref`, and so on. For the common case of two groups
#' this reduces to the original `trt`, `lsm_ref` and `lsm_alt` naming, ensuring backwards
#' compatibility.
#'
#' By default a treatment effect is calculated for every non-reference group versus the
#' reference group. Alternatively, a bespoke set of contrasts can be requested via the
#' `group_contrasts` argument of [set_vars()]; see its documentation for details. When a
#' contrast is between two non-reference groups it is named `trt_<minuend>_<subtrahend>`
#' using the corresponding `ref`/`alt` labels, e.g. `trt_alt2_alt` for `alt2` vs `alt`.
#'
#' If you want to include interaction terms in your model this can be done
#' by providing them to the `covariates` argument of [set_vars()]
#' e.g. `set_vars(covariates = c("sex*age"))`.
#'
#' Note that the treatment effects (`trt`, `trt_alt2`, ...) are the relevant linear
#' combinations of the model coefficients, i.e. the group main-effect contrasts evaluated
#' at the reference level of any covariates. The least square means (`lsm_*`) are instead
#' computed according to the requested `weights`. When `group` interacts with a covariate
#' these two quantities differ, so `trt` is not in general equal to `lsm_alt - lsm_ref`.
#' This matches the behaviour of the original two-group implementation, where `trt` has
#' always been the model coefficient.
#'
#' @inheritSection lsmeans Weighting
#'
#' @seealso [analyse()]
#' @seealso [stats::lm()]
#' @seealso [set_vars()]
#' @return
#' A named list with one set of entries per visit, each suffixed by the visit name.
#' For each visit the list contains:
#'
#' - the estimated treatment effect(s) (`trt_<visit>` for the `alt` vs `ref` comparison,
#'   `trt_alt2_<visit>`, `trt_alt3_<visit>`, ... for further non-reference groups vs the
#'   reference group, and `trt_<minuend>_<subtrahend>_<visit>` for custom contrasts
#'   between two non-reference groups requested via `group_contrasts`), and
#' - the least square means for each group (`lsm_ref_<visit>`, `lsm_alt_<visit>`,
#'   `lsm_alt2_<visit>`, ...).
#'
#' For the common case of two groups this reduces to `trt_<visit>`, `lsm_ref_<visit>`
#' and `lsm_alt_<visit>`. Each of these elements is itself a list holding the estimate
#' (`est`), standard error (`se`) and degrees of freedom (`df`).
#'
#' @examples
#' # Simulate a small dataset with a single visit, a treatment group and a
#' # baseline covariate to adjust for.
#' set.seed(101)
#' dat <- data.frame(
#'     visit = factor("visit_1"),
#'     group = factor(rep(c("Control", "Intervention"), each = 50)),
#'     basval = rnorm(100)
#' )
#' dat$outcome <- 5 + 2 * (dat$group == "Intervention") + dat$basval + rnorm(100)
#'
#' vars <- set_vars(
#'     outcome = "outcome",
#'     group = "group",
#'     visit = "visit",
#'     covariates = "basval"
#' )
#'
#' # Estimated treatment effect and least square means for the single visit.
#' # In a full `rbmi` analysis, `ancova()` is passed to `analyse()` rather than
#' # called directly; see [analyse()].
#' ancova(dat, vars)
#'
#' # Multi-arm ANCOVA with a bespoke set of contrasts. With three groups the
#' # default would compare each active arm against the reference ("Placebo");
#' # here we additionally request the "High" vs "Low" contrast.
#' set.seed(102)
#' dat3 <- data.frame(
#'     visit = factor("visit_1"),
#'     group = factor(
#'         rep(c("Placebo", "Low", "High"), each = 50),
#'         levels = c("Placebo", "Low", "High")
#'     ),
#'     basval = rnorm(150)
#' )
#' dat3$outcome <- 5 +
#'     2 * (dat3$group == "Low") +
#'     4 * (dat3$group == "High") +
#'     dat3$basval +
#'     rnorm(150)
#'
#' vars3 <- set_vars(
#'     outcome = "outcome",
#'     group = "group",
#'     visit = "visit",
#'     covariates = "basval",
#'     group_contrasts = list(
#'         c("Low", "Placebo"),
#'         c("High", "Placebo"),
#'         c("High", "Low")
#'     )
#' )
#'
#' # Output names: `trt` (Low - Placebo), `trt_alt2` (High - Placebo),
#' # `trt_alt2_alt` (High - Low), plus `lsm_ref` / `lsm_alt` / `lsm_alt2`.
#' names(ancova(dat3, vars3))
#'
#' @export
ancova <- function(
    data,
    vars,
    visits = NULL,
    weights = c("counterfactual", "equal", "proportional_em", "proportional")
) {
    ancova_core(
        data = data,
        vars = vars,
        visits = visits,
        weights = weights
    )
}


#' Core ANCOVA Implementation
#'
#' Internal function that provides the common functionality for the (multi-arm) ANCOVA
#' analysis. This function handles input validation, visit processing, delegates the
#' actual single-visit analysis to [ancova_single()], and assembles the per-parameter
#' metadata.
#'
#' @inheritParams ancova
#'
#' @keywords internal
ancova_core <- function(
    data,
    vars,
    visits = NULL,
    weights = c("counterfactual", "equal", "proportional_em", "proportional")
) {
    outcome <- vars[["outcome"]]
    group <- vars[["group"]]
    covariates <- vars[["covariates"]]
    visit <- vars[["visit"]]
    group_contrasts <- vars[["group_contrasts"]]
    weights <- match.arg(weights)

    expected_vars <- c(extract_covariates(covariates), outcome, group)

    assert_that(
        !any(visit %in% expected_vars),
        msg = paste0(
            "The `vars$visit` variable cannot be a covariate in an ANCOVA model. ",
            "Please adjust `vars$covariates` accordingly"
        )
    )

    for (var in c(visit, expected_vars)) {
        assert_that(
            var %in% names(data),
            msg = sprintf("Variable `%s` doesn't exist in data", var)
        )
    }

    assert_that(
        is.character(outcome),
        length(outcome) == 1,
        msg = "`vars$outcome` must be a length 1 character"
    )

    assert_that(
        is.character(group),
        length(group) == 1,
        msg = "`vars$group` must be a length 1 character"
    )

    assert_that(
        is.character(visit),
        length(visit) == 1,
        msg = "`vars$visit` must be a length 1 character"
    )

    assert_that(
        is.character(covariates) | is.null(covariates),
        msg = "`covariates` must be a character vector"
    )

    assert_that(
        is.null(visits) | is.character(visits),
        msg = "`visits` must be NULL or a character vector"
    )

    if (is.null(visits)) {
        visits <- unique(data[[visit]])
    }

    for (i in visits) {
        assert_that(
            i %in% data[[visit]],
            msg = sprintf(
                "Visit `%s` does not appear in `data[[vars$visit]]`",
                i
            )
        )
    }

    res <- lapply(
        visits,
        function(x) {
            data2 <- data[data[[visit]] == x, ]
            fit <- ancova_single(
                data2,
                outcome,
                group,
                covariates,
                weights,
                group_contrasts
            )
            meta <- attr(fit, "rbmi_par_meta")
            names(fit) <- paste0(names(fit), "_", x)
            meta[["parameter"]] <- paste0(meta[["parameter"]], "_", x)
            meta[["visit"]] <- x
            attr(fit, "rbmi_par_meta") <- meta
            fit
        }
    )
    par_meta <- do.call(rbind, lapply(res, attr, "rbmi_par_meta"))
    par_meta[["group"]] <- group
    par_meta <- par_meta[,
        c(
            "parameter",
            "estimate_type",
            "group",
            "group_level_1",
            "group_level_2",
            "visit"
        )
    ]
    rownames(par_meta) <- NULL

    out <- unlist(res, recursive = FALSE)
    attr(out, "rbmi_par_meta") <- par_meta
    return(out)
}


#' Implements an Analysis of Covariance (ANCOVA)
#'
#' @description
#' Performance analysis of covariance. See [ancova()] for full details.
#'
#' @param outcome Character, the name of the outcome variable in `data`.
#' @param group Character, the name of the group variable in `data`.
#' @param covariates Character vector containing the name of any additional covariates
#' to be included in the model as well as any interaction terms.
#'
#' @inheritParams ancova
#' @inheritSection lsmeans Weighting
#'
#' @param group_contrasts Optional list specifying bespoke treatment-group contrasts.
#' See [set_vars()] and [ancova()] for details. If `NULL` (default) a contrast of each
#' non-reference group versus the reference group is calculated.
#'
#' @details
#' - `group` must be a factor variable with two or more levels, all of which must be
#'   observed in the data.
#' - `outcome` must be a continuous numeric variable.
#'
#' The group levels are mapped to a fixed set of labels (`ref`, `alt`, `alt2`, ...) based
#' on the factor level ordering; see [ancova()] for the resulting naming scheme.
#'
#' @section Reserved Variable Names:
#' This function uses `"rbmiGroup"` as an internal variable name. If your dataset
#' contains a variable with this name, the function will error.
#'
#' @examples
#' \dontrun{
#' iris2 <- iris[ iris$Species %in% c("versicolor", "virginica"), ]
#' iris2$Species <- factor(iris2$Species)
#' ancova_single(iris2, "Sepal.Length", "Species", c("Petal.Length * Petal.Width"))
#' }
#' @seealso [ancova()]
#' @importFrom stats lm coef vcov df.residual
#' @keywords internal
ancova_single <- function(
    data,
    outcome,
    group,
    covariates,
    weights = c("counterfactual", "equal", "proportional_em", "proportional"),
    group_contrasts = NULL
) {
    weights <- match.arg(weights)
    assert_that(
        is.factor(data[[group]]),
        length(levels(data[[group]])) >= 2,
        length(unique(data[[group]])) == length(levels(data[[group]])),
        msg = paste(
            "`data[[vars$group]]` must be a factor variable with two or more levels,",
            "all of which must be observed in the data"
        )
    )
    assert_that(
        !"rbmiGroup" %in% names(data),
        msg = paste(
            "`rbmiGroup` is a reserved variable name for internal use, please rename",
            "your variable to avoid conflicts"
        )
    )

    orig_levels <- levels(data[[group]])
    n_lvl <- length(orig_levels)
    labels <- ancova_group_labels(n_lvl)
    intcode <- paste0("L", seq_len(n_lvl))

    # Standardise the group levels + variable name so that coefficient / term
    # extraction is robust to whitespace or special characters in the user levels.
    data2 <- data[, c(extract_covariates(covariates), outcome, group)]
    data2[["rbmiGroup"]] <- factor(
        intcode[as.integer(data2[[group]])],
        levels = intcode
    )
    data2 <- data2[!names(data2) %in% group]

    frm <- as_simple_formula(outcome, c(covariates, group))
    frm <- frm_find_and_replace(frm, as.name(group), as.name("rbmiGroup"))

    mod <- lm(formula = frm, data = data2)
    beta <- coef(mod)
    vcov_mod <- vcov(mod)
    df_res <- df.residual(mod)

    # Least square means for every group level
    lsm <- lapply(intcode, function(code) {
        args <- list(model = mod, .weights = weights)
        args[["rbmiGroup"]] <- code
        do.call(lsmeans, args)
    })
    names(lsm) <- paste0("lsm_", labels)

    # Contrasts to compute, as pairs of 1-based level indices (minuend first).
    contrasts <- ancova_resolve_contrasts(group_contrasts, orig_levels)

    trt <- lapply(contrasts, function(pair) {
        ancova_linear_contrast(
            pair[[1]],
            pair[[2]],
            beta,
            vcov_mod,
            df_res,
            intcode
        )
    })
    names(trt) <- vapply(
        contrasts,
        function(pair) ancova_contrast_name(pair[[1]], pair[[2]], labels),
        character(1)
    )

    res <- append(trt, lsm)

    # Parameter metadata (uses the actual group level labels, not ref/alt)
    meta_trt <- data.frame(
        parameter = names(trt),
        estimate_type = "contrast",
        group_level_1 = vapply(
            contrasts,
            function(p) orig_levels[p[[1]]],
            character(1)
        ),
        group_level_2 = vapply(
            contrasts,
            function(p) orig_levels[p[[2]]],
            character(1)
        ),
        stringsAsFactors = FALSE
    )
    meta_lsm <- data.frame(
        parameter = names(lsm),
        estimate_type = "lsm",
        group_level_1 = orig_levels,
        group_level_2 = NA_character_,
        stringsAsFactors = FALSE
    )
    attr(res, "rbmi_par_meta") <- rbind(meta_trt, meta_lsm)
    res
}


#' ANCOVA group level labels
#'
#' Maps the ordered factor levels of the group variable to the fixed `rbmi` label
#' scheme: the first level is `ref`, the second `alt`, and any further levels
#' `alt2`, `alt3`, etc.
#'
#' @param n Integer, the number of group levels.
#' @return A character vector of labels of length `n`.
#' @keywords internal
ancova_group_labels <- function(n) {
    vapply(
        seq_len(n),
        function(i) {
            if (i == 1) {
                "ref"
            } else if (i == 2) {
                "alt"
            } else {
                paste0("alt", i - 1)
            }
        },
        character(1)
    )
}


#' Name an ANCOVA treatment-effect contrast
#'
#' Determines the parameter name for a contrast between two group levels (given by
#' their 1-based factor level indices). Contrasts against the reference level use the
#' backwards-compatible `trt` / `trt_alt2` / ... naming; contrasts between two
#' non-reference levels are named `trt_<minuend>_<subtrahend>`.
#'
#' @param i Integer, 1-based index of the minuend (active) group level.
#' @param j Integer, 1-based index of the subtrahend (comparator) group level.
#' @param labels Character vector of level labels as returned by [ancova_group_labels()].
#' @return A length 1 character vector with the parameter name.
#' @keywords internal
ancova_contrast_name <- function(i, j, labels) {
    if (j == 1) {
        if (i == 2) {
            "trt"
        } else {
            paste0("trt_", labels[i])
        }
    } else {
        paste0("trt_", labels[i], "_", labels[j])
    }
}


#' Resolve the set of ANCOVA contrasts to compute
#'
#' Translates the optional `group_contrasts` specification into a list of 1-based
#' level index pairs (minuend first). When `group_contrasts` is `NULL` the default is
#' each non-reference level versus the reference level.
#'
#' @param group_contrasts Either `NULL` or a list of length-2 character vectors, each
#'   giving `c(minuend, subtrahend)` using the actual group level labels.
#' @param orig_levels Character vector of the group factor levels (in order).
#' @return A list of length-2 integer vectors giving `c(minuend, subtrahend)` indices.
#' @keywords internal
ancova_resolve_contrasts <- function(group_contrasts, orig_levels) {
    n_lvl <- length(orig_levels)
    if (is.null(group_contrasts)) {
        return(lapply(seq_len(n_lvl)[-1], function(i) c(i, 1L)))
    }
    assert_that(
        is.list(group_contrasts),
        length(group_contrasts) >= 1,
        msg = "`vars$group_contrasts` must be a non-empty list of length-2 character vectors"
    )
    pairs <- lapply(group_contrasts, function(ct) {
        assert_that(
            is.character(ct),
            length(ct) == 2,
            msg = "Each element of `vars$group_contrasts` must be a length-2 character vector"
        )
        idx <- match(ct, orig_levels)
        assert_that(
            !any(is.na(idx)),
            msg = sprintf(
                "`vars$group_contrasts` references group level(s) not present in the data: %s",
                paste(ct[is.na(idx)], collapse = ", ")
            )
        )
        assert_that(
            idx[[1]] != idx[[2]],
            msg = "`vars$group_contrasts` cannot contrast a group level with itself"
        )
        c(idx[[1]], idx[[2]])
    })
    keys <- vapply(pairs, paste, collapse = "-", FUN.VALUE = character(1))
    assert_that(
        !any(duplicated(keys)),
        msg = "`vars$group_contrasts` contains duplicate contrasts"
    )
    pairs
}


#' Compute a single ANCOVA linear contrast
#'
#' Evaluates a linear contrast between two group levels as a linear combination of the
#' model coefficients. For a contrast versus the reference level this reduces exactly to
#' the corresponding group coefficient (preserving backwards compatibility with the
#' two-group implementation).
#'
#' @param i Integer, 1-based index of the minuend (active) group level.
#' @param j Integer, 1-based index of the subtrahend (comparator) group level.
#' @param beta Numeric vector of model coefficients.
#' @param vcov_mod Variance-covariance matrix of the model coefficients.
#' @param df_res Residual degrees of freedom.
#' @param intcode Character vector of standardised level codes (e.g. `"L1"`, `"L2"`).
#' @return A list with elements `est`, `se` and `df`.
#'
#' @details
#' The contrast vector is built by looking up each group's coefficient by name rather
#' than assuming the reference level has no explicit coefficient. In the usual
#' intercept model the reference level (`rbmiGroupL1`) is absorbed by the intercept and
#' has no coefficient, so its contribution is correctly omitted. If the model has no
#' intercept every level receives its own coefficient (including `rbmiGroupL1`); looking
#' the coefficient up by name ensures the reference level is still subtracted rather than
#' silently returning the minuend group's absolute mean. Any *other* missing or aliased
#' (`NA`) coefficient indicates a rank-deficient design and triggers an error rather than
#' a silently dropped term.
#' @keywords internal
ancova_linear_contrast <- function(i, j, beta, vcov_mod, df_res, intcode) {
    assert_that(
        i %in% seq_along(intcode),
        j %in% seq_along(intcode),
        msg = "contrast indices are out of range of `intcode`"
    )
    assert_that(
        is.numeric(beta),
        !is.null(names(beta)),
        identical(names(beta), colnames(vcov_mod)),
        length(beta) == nrow(vcov_mod),
        msg = "`beta` and `vcov_mod` must be aligned by name and dimension"
    )
    has_intercept <- "(Intercept)" %in% names(beta)
    lvec <- numeric(length(beta))
    names(lvec) <- names(beta)
    for (k in c(i, j)) {
        name_k <- paste0("rbmiGroup", intcode[k])
        # The reference level (k == 1) legitimately has no coefficient when the
        # model has an intercept (it is the baseline); any other missing or
        # aliased coefficient means a rank-deficient design and must error.
        if (has_intercept && k == 1) next
        assert_that(
            name_k %in% names(beta) && !is.na(beta[[name_k]]),
            msg = sprintf(
                "ANCOVA contrast requires coefficient `%s`, which is missing or aliased; the design matrix is rank-deficient",
                name_k
            )
        )
        lvec[[name_k]] <- if (k == i) 1 else -1
    }
    list(
        est = sum(lvec * beta),
        se = sqrt(drop(t(lvec) %*% vcov_mod %*% lvec)),
        df = df_res
    )
}
