#' MMRM Analysis Function for Imputed Datasets
#'
#' Fits a Mixed Model for Repeated Measures (MMRM) to an imputed dataset and
#' returns per-visit treatment contrasts, least square means, and residual
#' variance estimates in the format required by [analyse()].
#'
#' @param data A `data.frame` as provided by [analyse()].
#' @param vars A `vars` object as generated by [set_vars()]. The `subjid`,
#'   `group`, `visit`, `outcome`, and `covariates` elements are used.
#' @param visits An optional character vector of visits to extract results for.
#'   If `NULL` all visits in `data[[vars$visit]]` are used.
#' @param cov_struct Character. Covariance structure passed to [mmrm::mmrm()].
#'   Must be one of `"us"` (default), `"ad"`, `"adh"`, `"ar1"`, `"ar1h"`,
#'   `"cs"`, `"csh"`, `"toep"`, or `"toeph"`.
#' @param weights Character. Weighting strategy for least square means passed to
#'   [emmeans::emmeans()]. Either `"proportional"` (default, equivalent to
#'   counterfactual/g-computation) or `"equal"`.
#' @param ... Additional arguments passed to [mmrm::mmrm()], in particular
#'   `method` and `vcov` to control degrees of freedom and variance-covariance
#'   adjustments, and `reml` to switch between REML and ML estimation.
#'
#' @details
#' A single MMRM is fit across all visits using [mmrm::mmrm()]. The model
#' formula is:
#' ```
#' outcome ~ group + visit + covariates + cov_struct(visit | subjid)
#' ```
#' Note that the `group:visit` interaction is **not** included by default.
#' Add it explicitly via `vars$covariates` if required, e.g.
#' `set_vars(covariates = c("group*visit"))`.
#'
#' Per-visit marginal means and treatment contrasts are extracted via
#' [emmeans::emmeans()] using Satterthwaite degrees of freedom.
#'
#' The return format uses arm-labelled names for all groups:
#' ```
#' list(
#'     var_B_visit_1  = list(est = ..., se = ..., df = ...),
#'     trt_B_visit_1  = list(est = ..., se = ..., df = ...),
#'     lsm_A_visit_1  = list(est = ..., se = ..., df = ...),
#'     lsm_B_visit_1  = list(est = ..., se = ..., df = ...),
#'     ...
#' )
#' ```
#' where `A` is the reference (first factor level of `vars$group`) and `B` is
#' the treatment arm. For 3+ arms, one `var_*` and `trt_*` entry is produced
#' per non-reference arm.
#'
#' `var_<arm>_<visit>` is the diagonal element of the MMRM residual covariance
#' matrix at that visit (i.e. the marginal residual variance). Its `se` and
#' `df` are taken from the corresponding treatment contrast.
#'
#' @seealso [analyse()], [ancova()], [mmrm::mmrm()]
#' @importFrom emmeans emmeans contrast
#' @importFrom stats as.formula
#' @export
mmrm_analyse <- function(
    data,
    vars,
    visits = NULL,
    cov_struct = c("us", "ad", "adh", "ar1", "ar1h", "cs", "csh", "toep", "toeph"),
    weights = c("proportional", "equal"),
    ...
) {
    cov_struct <- match.arg(cov_struct)
    weights    <- match.arg(weights)

    subjid     <- vars[["subjid"]]
    outcome    <- vars[["outcome"]]
    group      <- vars[["group"]]
    visit      <- vars[["visit"]]
    covariates <- vars[["covariates"]]

    for (var in c(subjid, outcome, group, visit)) {
        assert_that(
            var %in% names(data),
            msg = sprintf("Variable `%s` doesn't exist in data", var)
        )
    }

    if (!is.factor(data[[group]])) {
        data[[group]] <- factor(data[[group]])
    }
    if (!is.factor(data[[visit]])) {
        data[[visit]] <- factor(data[[visit]])
    }

    assert_that(
        length(levels(data[[group]])) >= 2,
        msg = "`vars$group` must have at least 2 levels"
    )

    if (is.null(visits)) {
        visits <- as.character(levels(data[[visit]]))
    }

    for (v in visits) {
        assert_that(
            v %in% levels(data[[visit]]),
            msg = sprintf("Visit `%s` does not appear in `data[[vars$visit]]`", v)
        )
    }

    data <- data[data[[visit]] %in% visits, , drop = FALSE]
    data[[visit]] <- droplevels(data[[visit]])
    visits <- as.character(levels(data[[visit]]))

    fit <- mmrm_analyse_fit(data, outcome, group, visit, subjid, covariates, cov_struct, ...)

    res <- lapply(visits, function(v) {
        r <- mmrm_analyse_single(fit, visit_level = v, visit = visit, group = group, weights = weights)
        names(r) <- paste0(names(r), "_", v)
        r
    })
    unlist(res, recursive = FALSE)
}


#' Fit MMRM for use in [mmrm_analyse()]
#'
#' Builds the model formula and calls [mmrm::mmrm()].
#'
#' @param data A `data.frame`.
#' @param outcome,group,visit,subjid,covariates Variable name strings.
#' @param cov_struct Covariance structure string.
#' @param ... Passed to [mmrm::mmrm()].
#' @keywords internal
mmrm_analyse_fit <- function(data, outcome, group, visit, subjid, covariates, cov_struct, ...) {
    covariates_part  <- paste(covariates, collapse = " + ")
    grp_visit_part   <- paste(group, "+", visit)
    random_eff_part  <- sprintf("%s(%s | %s)", cov_struct, visit, subjid)

    rhs <- paste(grp_visit_part, "+", random_eff_part)
    if (nchar(covariates_part) > 0) {
        rhs <- paste(covariates_part, "+", rhs)
    }

    frm <- as.formula(paste(outcome, "~", rhs))
    mmrm::mmrm(formula = frm, data = data, ...)
}


#' Extract per-visit results from a fitted MMRM
#'
#' @param fit An `mmrm` object from [mmrm_analyse_fit()].
#' @param visit_level Character. The visit level to extract.
#' @param visit,group Variable name strings.
#' @param weights Weighting strategy for [emmeans::emmeans()].
#' @return Named list with `var_<arm>`, `trt_<arm>`, and `lsm_<arm>` entries
#'   (without the visit suffix, which is appended by [mmrm_analyse()]).
#' @keywords internal
mmrm_analyse_single <- function(fit, visit_level, visit, group, weights) {
    data       <- mmrm::component(fit, "full_frame")
    grp_levels <- levels(data[[group]])
    ref_level  <- grp_levels[[1]]
    alt_levels <- grp_levels[-1]

    visit_at_level <- stats::setNames(list(visit_level), visit)
    em_res <- emmeans::emmeans(
        fit,
        specs   = group,
        by      = visit,
        at      = visit_at_level,
        weights = weights
    )
    em_df <- as.data.frame(em_res)

    vc      <- mmrm::VarCorr(fit)
    var_est <- vc[visit_level, visit_level]

    cont_res <- emmeans::contrast(em_res, "trt.vs.ctrl", ref = ref_level)
    cont_df  <- as.data.frame(cont_res)

    # df source: contrast df (rounded), stable across imputations.
    # lsm Satterthwaite df vary per imputation and break pool_internal.rubin.
    # Map each arm to its contrast df: alt arms use their own contrast row;
    # ref arm uses the first alt arm's contrast df (same visit, same model).
    get_cont_row <- function(arm) {
        cont_df[cont_df[["contrast"]] == paste(arm, "-", ref_level), , drop = FALSE]
    }
    ref_cont_row <- get_cont_row(alt_levels[[1]])

    all_lsm <- lapply(grp_levels, function(arm) {
        em_row   <- em_df[em_df[[group]] == arm, , drop = FALSE]
        cont_row <- if (arm == ref_level) ref_cont_row else get_cont_row(arm)
        list(est = em_row[["emmean"]], se = em_row[["SE"]], df = round(cont_row[["df"]]))
    })
    names(all_lsm) <- paste0("lsm_", grp_levels)

    all_trt <- lapply(alt_levels, function(arm) {
        row <- get_cont_row(arm)
        list(est = row[["estimate"]], se = row[["SE"]], df = round(row[["df"]]))
    })
    names(all_trt) <- paste0("trt_", alt_levels)

    # var entries: residual variance estimate; se/df from the corresponding contrast
    all_var <- lapply(alt_levels, function(arm) {
        row <- get_cont_row(arm)
        list(est = var_est, se = row[["SE"]], df = round(row[["df"]]))
    })
    names(all_var) <- paste0("var_", alt_levels)

    c(all_var, all_trt, all_lsm)
}
